# Generated by Django 6.0.4 on 2026-06-03 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_case', '0002_legalcase_lawyer_alter_legalcase_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='LawyerAcceptCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='acceptance', to='legal_case.legalcase')),
            ],
        ),
    ]
