# Generated by Django 6.0.4 on 2026-06-09 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_case', '0005_legalcase_accepted_at_alter_legalcase_lawyer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalcase',
            name='channel',
            field=models.CharField(choices=[('web', 'Web'), ('mobile', 'Mobile'), ('ussd', 'USSD')], default='web', max_length=20),
        ),
    ]
