# Generated by Django 6.0.4 on 2026-06-01 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_lawyerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ussd_session_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
