# Generated by Django 6.0.4 on 2026-06-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_ussd_session_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lawyerprofile',
            old_name='specializations',
            new_name='law_firm',
        ),
        migrations.RemoveField(
            model_name='lawyerprofile',
            name='bar_number',
        ),
        migrations.RemoveField(
            model_name='lawyerprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='lawyerprofile',
            name='is_pro_bono',
        ),
        migrations.RemoveField(
            model_name='lawyerprofile',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='lawyerprofile',
            name='license_number',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
