# Generated by Django 6.0.4 on 2026-06-01 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyerprofile',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='lawyerprofile',
            name='specialization',
            field=models.CharField(choices=[('criminal', 'Criminal Law'), ('civil', 'Civil Law'), ('family', 'Family Law'), ('corporate', 'Corporate Law'), ('intellectual_property', 'Intellectual Property Law'), ('labor', 'Labor Law'), ('tax', 'Tax Law'), ('environmental', 'Environmental Law'), ('international', 'International Law'), ('other', 'Other')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
