# Generated by Django 6.0.4 on 2026-06-09 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
        ('legal_case', '0005_legalcase_accepted_at_alter_legalcase_lawyer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='case',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='legal_case.legalcase'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conversation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
